name: Comment on GitHub
author: Dao Hoang Son <dao@hoangson.vn>
description: Leaves a comment on matching PR or commit.
branding:
  icon: 'message-square'  
  color: 'blue'
inputs:
  message: 
    description: Comment's message
    required: true
runs:
  using: 'node12'
  main: 'index.js'
