name: Comment on GitHub
author: Dao Hoang Son <dao@hoangson.vn>
description: Leaves a comment on matching PR or commit.
branding:
  icon: message-square
  color: blue
inputs:
  body: 
    description: Comment body
    required: true
  fingerprint:
    description: The text that will be appended to `body` and used to auto-merge comments
    required: false
  replace:
    description: Whether the comment should be replaced instead of being appended on fingerprint match
    required: false
outputs:
  action:
    description: Whether the comment has been `created` or `updated`
  target:
    description: Whether the comment has been made in a `commit_comment`, `pull_comment` or `release`
  url:
    description: The comment URL
runs:
  using: node12
  main: dist/index.min.js
